#!/bin/bash -x

increment_version ()
{
    declare -a part=( ${1//\./ } )
    declare    new
    declare -i carry=1

    for (( CNTR=${#part[@]}-1; CNTR>=0; CNTR-=1 )); do
        len=${#part[CNTR]}
        new=$((part[CNTR]+carry))
        [ ${#new} -gt $len ] && carry=1 || carry=0
        [ $CNTR -gt 0 ] && part[CNTR]=${new: -len} || part[CNTR]=${new}
    done
    new="${part[*]}"
    echo -e "${new// /.}"
}

OLD_TAG=$(git describe --abbrev=0 --tags)
rc=$?

set -e

if [[ $rc != 0 ]];
then
    OLD_TAG=0.0.0;
fi

git remote add auth https://$GIT_USER:$GIT_PASS@bitbucket.org/$BITBUCKET_REPO_OWNER/$BITBUCKET_REPO_SLUG.git

NEW_TAG=$(increment_version $LATEST_TAG)

echo -c "Old version: $OLD_TAG \nNew version: $NEW_TAG""

git tag $NEW_TAG $BITBUCKET_COMMIT

git push auth $NEW_TAG
